//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAppointment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAppointment()
        {
            this.tblPrescriptionMasters = new HashSet<tblPrescriptionMaster>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Cid { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Stastus { get; set; }
        public Nullable<int> DrId { get; set; }
    
        public virtual tblCasePaper tblCasePaper { get; set; }
        public virtual tblDoctor tblDoctor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPrescriptionMaster> tblPrescriptionMasters { get; set; }
    }
}
