//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMedicine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMedicine()
        {
            this.tblprescripationMedicineDetails = new HashSet<tblprescripationMedicineDetail>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string MContent { get; set; }
        public string Company { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblprescripationMedicineDetail> tblprescripationMedicineDetails { get; set; }
    }
}
