//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblmaterial
    {
        public int id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> Totalprice { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<int> Gstid { get; set; }
    
        public virtual tblGst tblGst { get; set; }
    }
}
