//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPatientfeeDetail
    {
        public int id { get; set; }
        public Nullable<int> pmid { get; set; }
        public Nullable<int> Feeid { get; set; }
        public Nullable<double> feeprice { get; set; }
    }
}
