//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblprescripationMedicineDetail
    {
        public int Id { get; set; }
        public Nullable<int> prid { get; set; }
        public Nullable<int> medicineid { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<bool> MDose { get; set; }
        public Nullable<bool> AfDose { get; set; }
        public Nullable<bool> NDose { get; set; }
    
        public virtual tblMedicine tblMedicine { get; set; }
        public virtual tblPrescriptionMaster tblPrescriptionMaster { get; set; }
    }
}
