//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPrescriptionMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPrescriptionMaster()
        {
            this.Fees = new HashSet<Fee>();
            this.tblprescripationMedicineDetails = new HashSet<tblprescripationMedicineDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Aid { get; set; }
        public string Naration { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public string Symtam { get; set; }
        public string Disiese { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fee> Fees { get; set; }
        public virtual tblAppointment tblAppointment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblprescripationMedicineDetail> tblprescripationMedicineDetails { get; set; }
    }
}
